l=int(input("enter the	value of length"))
b=int(input("enter the value of breadth"))
h=int(input("enter the value of height"))
paintable_area=(l*b+h*b+h*b+h*l+h*l)
coverage_area=(paintable_area/10)
price_per_liter=(200*coverage_area)
print("paintable_area",paintable_area)
print("coverage_area",coverage_area)	
print("price_per_liter",price_per_liter)